package com.huanghh.diary.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huanghh.diary.mvp.model.DiaryItem;
import com.huanghh.diary.mvp.model.WeeItem;

import com.huanghh.diary.dao.DiaryItemDao;
import com.huanghh.diary.dao.WeeItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryItemDaoConfig;
    private final DaoConfig weeItemDaoConfig;

    private final DiaryItemDao diaryItemDao;
    private final WeeItemDao weeItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryItemDaoConfig = daoConfigMap.get(DiaryItemDao.class).clone();
        diaryItemDaoConfig.initIdentityScope(type);

        weeItemDaoConfig = daoConfigMap.get(WeeItemDao.class).clone();
        weeItemDaoConfig.initIdentityScope(type);

        diaryItemDao = new DiaryItemDao(diaryItemDaoConfig, this);
        weeItemDao = new WeeItemDao(weeItemDaoConfig, this);

        registerDao(DiaryItem.class, diaryItemDao);
        registerDao(WeeItem.class, weeItemDao);
    }
    
    public void clear() {
        diaryItemDaoConfig.clearIdentityScope();
        weeItemDaoConfig.clearIdentityScope();
    }

    public DiaryItemDao getDiaryItemDao() {
        return diaryItemDao;
    }

    public WeeItemDao getWeeItemDao() {
        return weeItemDao;
    }

}
