package com.huanghh.diary.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huanghh.diary.mvp.model.Wee;
import com.huanghh.diary.mvp.model.Diary;

import com.huanghh.diary.dao.WeeDao;
import com.huanghh.diary.dao.DiaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weeDaoConfig;
    private final DaoConfig diaryDaoConfig;

    private final WeeDao weeDao;
    private final DiaryDao diaryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weeDaoConfig = daoConfigMap.get(WeeDao.class).clone();
        weeDaoConfig.initIdentityScope(type);

        diaryDaoConfig = daoConfigMap.get(DiaryDao.class).clone();
        diaryDaoConfig.initIdentityScope(type);

        weeDao = new WeeDao(weeDaoConfig, this);
        diaryDao = new DiaryDao(diaryDaoConfig, this);

        registerDao(Wee.class, weeDao);
        registerDao(Diary.class, diaryDao);
    }
    
    public void clear() {
        weeDaoConfig.clearIdentityScope();
        diaryDaoConfig.clearIdentityScope();
    }

    public WeeDao getWeeDao() {
        return weeDao;
    }

    public DiaryDao getDiaryDao() {
        return diaryDao;
    }

}
